#!/bin/bash
# SessionStart hook: install a `gh` shim that routes the GitHub CLI around the
# outbound HTTPS proxy.
#
# The agent egress proxy (HTTPS_PROXY) enforces a policy that blocks some
# api.github.com operations — notably `gh run watch`, which long-polls — so the
# gh-based skills (/watch-ci, /check-merge, /finalize, …) stall. gh talks only to
# GitHub hosts and works fine connecting directly, so the proxy is stripped for
# gh alone. Everything else that legitimately needs the proxy is untouched.
#
# Remote-only: it no-ops when $CLAUDE_CODE_REMOTE is unset, so running `claude`
# against your own working tree does not shadow the `gh` you installed yourself.

set -euo pipefail

[ "${CLAUDE_CODE_REMOTE:-}" = "true" ] || exit 0

# $HOME/.local/bin is first on PATH, so a `gh` here shadows the real binary for
# every Bash tool shell this session spawns. The VM is ephemeral and the hook
# runs on every startup|resume, so recreating the shim each session is correct.
#
# Note to whoever gets to test this hook: both of those cut the other way on you.
# The shim is written from whatever `gh` the running PATH resolves, and it outlives
# the run — so invoking this file under a stubbed PATH repoints the session's own
# `gh` at the stub, and every later `gh` call fails once the stub is cleaned up.
# Point $HOME at a scratch directory instead and read the shim it writes there —
# under that $HOME the exclusion below no longer skips the session's own shim, so
# the exec line chains through it rather than naming the real binary, which is the
# test's doing and not the hook's.
shim_dir="${HOME}/.local/bin"

# Resolve the real gh, ignoring any shim a previous run left in shim_dir, so the
# shim never ends up exec'ing itself.
real_gh="$(PATH="$(printf '%s' "$PATH" | tr ':' '\n' | grep -vFx "$shim_dir" | paste -sd: -)" command -v gh || true)"

if [ -z "$real_gh" ]; then
  # stdout, not stderr: Claude Code folds a SessionStart hook's stdout into the
  # session context, and this notice is the only signal that the environment
  # setup script is unset or missing the gh install.
  cat <<'MSG'
session-start: `gh` is not on PATH, so the proxy shim was not installed.

Agent: relay this to the operator before running anything that needs `gh`
(most of the PR loop does). The environment setup script for this Claude Code
environment is either unset or does not install the GitHub CLI. They set it in
the session composer: the environment picker -> Cloud -> the environment's gear
icon. It needs at least:

    apt-get install -y gh

The script runs once when the environment snapshot is built, so the session has
to be restarted for it to take effect.
MSG
  exit 0
fi

mkdir -p "$shim_dir"
cat > "${shim_dir}/gh" <<EOF
#!/bin/bash
# Auto-generated by .claude/hooks/gh-shim.sh — do not edit by hand.
# Routes gh around the outbound HTTPS proxy (which blocks some api.github.com
# operations, e.g. long-polling \`gh run watch\`). See the hook for rationale.
exec env -u HTTPS_PROXY -u https_proxy ${real_gh} "\$@"
EOF
chmod +x "${shim_dir}/gh"
