#!/bin/bash
# SessionStart hook for Claude Code remote sessions.
#
# Two jobs, both remote-only (the hook no-ops when $CLAUDE_CODE_REMOTE is unset,
# so local dev sessions are unaffected and running `claude` against your working
# tree won't reinstall on every launch):
#
# 1. Install a `gh` shim that routes the GitHub CLI around the outbound HTTPS
#    proxy. The agent egress proxy (HTTPS_PROXY) enforces a policy that blocks
#    some api.github.com operations — notably `gh run watch`, which long-polls —
#    so the gh-based skills (/watch-ci, /check-merge, /finalize, …) stall. gh
#    talks only to GitHub hosts and works fine connecting directly, so we strip
#    the proxy for gh alone. Everything else that legitimately needs the proxy
#    is untouched.
#
# 2. Re-sync dependencies. Remote/web sessions can resume with a stale
#    dependency tree if the lockfile advanced since the environment snapshot was
#    built (the setup script runs once at snapshot build time, then is cached —
#    see https://code.claude.com/docs/en/claude-code-on-the-web#setup-scripts).
#    Re-running on every session start keeps the install tree tracking the
#    current lockfile.

set -euo pipefail

[ "${CLAUDE_CODE_REMOTE:-}" = "true" ] || exit 0

# --- 1. Install the proxy-stripping gh shim -------------------------------
# $HOME/.local/bin is first on PATH, so a `gh` here shadows the real binary for
# every Bash tool shell this session spawns. The VM is ephemeral and the hook
# runs on every startup|resume, so recreating the shim each session is correct.
install_gh_shim() {
  local shim_dir="${HOME}/.local/bin"
  # Resolve the real gh, ignoring any shim a previous run left in shim_dir, so
  # the shim never ends up exec'ing itself.
  local real_gh
  real_gh="$(PATH="$(printf '%s' "$PATH" | tr ':' '\n' | grep -vFx "$shim_dir" | paste -sd: -)" command -v gh || true)"
  if [ -z "$real_gh" ]; then
    echo "session-start: gh not found on PATH; skipping gh proxy shim." >&2
    return 0
  fi

  mkdir -p "$shim_dir"
  cat > "${shim_dir}/gh" <<EOF
#!/bin/bash
# Auto-generated by .claude/hooks/session-start.sh — do not edit by hand.
# Routes gh around the outbound HTTPS proxy (which blocks some api.github.com
# operations, e.g. long-polling \`gh run watch\`). See the hook for rationale.
exec env -u HTTPS_PROXY -u https_proxy ${real_gh} "\$@"
EOF
  chmod +x "${shim_dir}/gh"
}

install_gh_shim

# --- 2. Keep dependencies in sync with the lockfile -----------------------
cd "${CLAUDE_PROJECT_DIR:-$(pwd)}"

corepack enable pnpm >/dev/null 2>&1 || true
pnpm install --frozen-lockfile
