#!/usr/bin/env node

/**
 * Writes `docs/music/hidden-songs.md`, the list of every song still marked
 * `hidden: true`, by artist and then by album, each naming what it lacks:
 *
 *   pnpm music:hidden
 *
 * Like `pnpm styles:codegen` it **exits non-zero when it had to write**, which
 * is how `scripts/vet-songs.sh` fails on a stale list while leaving it current.
 */

import matter from 'gray-matter';
import fs from 'node:fs';
import path from 'node:path';
import { z } from 'zod';

import { PREAMBLE, splitSections } from '../src/pages/music/index.node-safe.ts';
import {
  MUSIC_ALBUM_SLUGS,
  MUSIC_PROJECT_NAMES,
  SONG_DESCRIPTION_PLACEHOLDER,
} from '../src/shared/music-catalogue/index.node-safe.ts';
import type { WithFilePath } from '../src/shared/typings/index.ts';
import { songFiles } from './lib/public-markdown.ts';

const LIST = 'docs/music/hidden-songs.md';
const LOCALES = ['en', 'ru'] as const;

const localeSchema = z.object({ description: z.string().optional() });

/** The few fields this list reads; the song schema itself is `server-only`. */
const hiddenSongSchema = z.object({
  title: z.string(),
  hidden: z.boolean().optional(),
  project: z.array(z.enum(MUSIC_PROJECT_NAMES)).min(1),
  album: z.enum(MUSIC_ALBUM_SLUGS).nullable().optional(),
  track: z.number().optional(),
  en: localeSchema.optional(),
  ru: localeSchema.optional(),
});

type HiddenSong = z.infer<typeof hiddenSongSchema> &
  WithFilePath & {
    lacks: string[];
  };

/** Whether text says anything once its HTML comments — scaffold notes — are gone. */
const says = (text: string) =>
  text.replaceAll(/<!--[\S\s]*?-->/g, '').trim() !== '';

type Locale = (typeof LOCALES)[number];

/** `what` bare when every locale lacks it, else prefixed by each one that does. */
function lacking(what: string, has: (locale: Locale) => boolean): string[] {
  const missing = LOCALES.filter((locale) => !has(locale));
  return missing.length === LOCALES.length
    ? [what]
    : missing.map((locale) => `${locale} ${what}`);
}

function lacks(song: z.infer<typeof hiddenSongSchema>, body: string) {
  const sections = splitSections(body);
  const tells = (key: string) => says(sections.get(key) ?? '');

  return [
    ...lacking('description', (locale) => {
      const description = song[locale]?.description?.trim();
      return (
        description !== undefined &&
        description !== SONG_DESCRIPTION_PLACEHOLDER
      );
    }),
    // The preamble is every locale's story, as the page reads it.
    ...lacking('story', (locale) => tells(PREAMBLE) || tells(`lang:${locale}`)),
  ];
}

function hiddenSongs(): HiddenSong[] {
  return songFiles().flatMap((file) => {
    const { data, content } = matter(fs.readFileSync(file, 'utf8'));
    const song = hiddenSongSchema.parse(data);
    return song.hidden === true
      ? [{ ...song, filePath: file, lacks: lacks(song, content) }]
      : [];
  });
}

const escaped = (text: string) =>
  text.replaceAll(/[*[\\\]_`]/g, String.raw`\$&`);

function entry({ title, filePath, lacks: missing }: HiddenSong): string {
  const link = path.relative(path.dirname(LIST), filePath);
  const status = missing.length === 0 ? 'ready' : missing.join(', ');
  return `- [${escaped(title)}](${link}) — ${status}`;
}

function byTrack(a: HiddenSong, b: HiddenSong): number {
  return (a.track ?? 0) - (b.track ?? 0) || a.title.localeCompare(b.title);
}

function section(heading: string, songs: HiddenSong[]): string[] {
  return songs.length === 0
    ? []
    : [heading, '', ...songs.toSorted(byTrack).map((song) => entry(song)), ''];
}

function render(songs: HiddenSong[]): string {
  const artists = MUSIC_PROJECT_NAMES.flatMap((artist) => {
    const theirs = songs.filter(({ project }) => project[0] === artist);
    if (theirs.length === 0) return [];

    return [
      `## ${artist}`,
      '',
      ...MUSIC_ALBUM_SLUGS.flatMap((album) =>
        section(
          `### ${album}`,
          theirs.filter((song) => song.album === album),
        ),
      ),
      ...section(
        '### Singles',
        theirs.filter((song) => (song.album ?? null) === null),
      ),
    ];
  });

  return [
    '# Hidden songs',
    '',
    '<!-- Generated by `pnpm music:hidden` from apps/vova/public/music/: edit a song, never this file. -->',
    '',
    `${songs.length} songs are hidden, each until it has a description and a story in both languages. A line names what its song still lacks, or reads “ready” once it lacks nothing and only its \`hidden: true\` is left to drop.`,
    '',
    ...artists,
  ].join('\n');
}

const next = render(hiddenSongs());
const current = fs.existsSync(LIST) ? fs.readFileSync(LIST, 'utf8') : '';

if (current === next) {
  process.stdout.write('music-hidden: current\n');
} else {
  // Renamed into place: vet's format check reads the list in the same fan-out.
  const staging = `${LIST}.tmp`;
  fs.mkdirSync(path.dirname(LIST), { recursive: true });
  fs.writeFileSync(staging, next);
  fs.renameSync(staging, LIST);
  process.stdout.write(`music-hidden: rewrote ${LIST}; commit it\n`);
  process.exit(1);
}
