#!/usr/bin/env python3
"""Tests for the export's agent/human labelling.

Run by path, as `scripts/vet.sh` does — see the note there on why never through
`unittest discover`.
"""

from __future__ import annotations

import unittest

from gh_export.authorship import attribution, split_agent_footer

BODY = "Fixed in abc123.\n\nThe root cause was the stale ref."

COMMENT_FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
HARNESS_FOOTER = (
    "\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)"
    "\n\nhttps://claude.ai/code/session_01JkHnXxThBXkhVJzKCuJji3"
)


class SplitAgentFooter(unittest.TestCase):
    def test_footer_marks_the_body_as_the_agent_s_and_is_removed(self) -> None:
        self.assertEqual(split_agent_footer(BODY + COMMENT_FOOTER), (True, BODY))

    def test_the_same_body_without_the_footer_is_a_human_s(self) -> None:
        self.assertEqual(split_agent_footer(BODY), (False, BODY))

    def test_both_link_targets_are_recognized(self) -> None:
        for url in ("https://claude.ai/code", "https://claude.com/claude-code"):
            with self.subTest(url=url):
                body = f"{BODY}\n\n---\n_Generated by [Claude Code]({url})_"
                self.assertEqual(split_agent_footer(body), (True, BODY))

    def test_both_verbs_are_recognized(self) -> None:
        for verb in ("by", "with"):
            with self.subTest(verb=verb):
                body = (
                    f"{BODY}\n\nGenerated {verb} "
                    "[Claude Code](https://claude.ai/code)"
                )
                self.assertEqual(split_agent_footer(body), (True, BODY))

    def test_the_harness_form_with_its_session_link_is_recognized(self) -> None:
        self.assertEqual(split_agent_footer(BODY + HARNESS_FOOTER), (True, BODY))

    def test_the_rule_above_the_footer_is_optional(self) -> None:
        body = f"{BODY}\n\n_Generated by [Claude Code](https://claude.ai/code)_"
        self.assertEqual(split_agent_footer(body), (True, BODY))

    def test_trailing_whitespace_after_the_footer_is_tolerated(self) -> None:
        self.assertEqual(
            split_agent_footer(BODY + COMMENT_FOOTER + "  \n\n  "), (True, BODY)
        )

    def test_a_body_that_is_only_the_footer_strips_to_empty(self) -> None:
        self.assertEqual(split_agent_footer(COMMENT_FOOTER.lstrip()), (True, ""))

    def test_a_footer_shaped_line_mid_body_is_prose(self) -> None:
        """An operator quoting the footer to discuss it must not export as the
        agent."""
        body = (
            "Every agent post ends with:\n\n"
            "---\n_Generated by [Claude Code](https://claude.ai/code)_\n\n"
            "Please keep it that way."
        )
        self.assertEqual(split_agent_footer(body), (False, body))

    def test_only_the_trailing_footer_is_stripped_when_one_is_also_quoted(
        self,
    ) -> None:
        quoted = (
            "The footer reads _Generated by "
            "[Claude Code](https://claude.ai/code)_\nand it stays."
        )
        self.assertEqual(split_agent_footer(quoted + COMMENT_FOOTER), (True, quoted))


class Attribution(unittest.TestCase):
    def test_the_label_annotates_the_login_rather_than_replacing_it(self) -> None:
        holder = {"login": "vzakharov"}
        self.assertEqual(attribution(holder, True), "@vzakharov (agent)")
        self.assertEqual(attribution(holder, False), "@vzakharov (human)")

    def test_a_missing_user_still_renders(self) -> None:
        self.assertEqual(attribution(None, False), "@? (human)")


if __name__ == "__main__":
    unittest.main()
